# Generated by Django 3.2.7 on 2022-03-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kzversion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exemples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=200, verbose_name='name')),
                ('data', models.DateField(auto_now=True)),
                ('teg', models.CharField(default=' ', max_length=100, verbose_name='teg')),
                ('title1', models.CharField(default=' ', max_length=500, verbose_name='Title1')),
                ('title2', models.CharField(blank=True, default=' ', max_length=500, verbose_name='Title2')),
                ('task2', models.TextField(blank=True, default=' ', verbose_name='Task2')),
                ('answe2', models.CharField(blank=True, default=' ', max_length=300, verbose_name='Answer2')),
                ('title3', models.CharField(blank=True, default=' ', max_length=500, verbose_name='Title3')),
                ('task1', models.TextField(blank=True, default=' ', verbose_name='Task3')),
                ('answe1', models.CharField(blank=True, default=' ', max_length=300, verbose_name='Answer3')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='kzversion.collection')),
                ('tags', models.ManyToManyField(related_name='task', to='kzversion.Teg')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
            },
        ),
    ]
