# Generated by Django 3.2.7 on 2022-03-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kzversion', '0002_exemples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lect',
            name='title',
        ),
        migrations.AddField(
            model_name='lect',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exemples',
            name='tags',
            field=models.ManyToManyField(related_name='exemples', to='kzversion.Teg'),
        ),
        migrations.AlterField(
            model_name='lect',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lect', to='kzversion.collection'),
        ),
        migrations.AlterField(
            model_name='lect',
            name='tags',
            field=models.ManyToManyField(related_name='lect', to='kzversion.Teg'),
        ),
        migrations.CreateModel(
            name='labwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('materials', models.CharField(blank=True, max_length=500, verbose_name='matrials')),
                ('data', models.DateField(auto_now=True)),
                ('text', models.TextField(verbose_name='Your article')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labwork', to='kzversion.collection')),
                ('tags', models.ManyToManyField(related_name='laborator', to='kzversion.Teg')),
            ],
            options={
                'verbose_name': 'Зертханалық жұмыс',
                'verbose_name_plural': 'Зертханалық жұмыстар',
            },
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('data', models.DateField(auto_now=True)),
                ('text', models.TextField(verbose_name='Some_text')),
                ('tags', models.ManyToManyField(related_name='examen', to='kzversion.Teg')),
            ],
            options={
                'verbose_name': 'Емтихан қағазы',
                'verbose_name_plural': 'Емтихан қағазылар',
            },
        ),
    ]
