# Generated by Django 3.2.7 on 2022-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kzversion', '0003_auto_20220312_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labwork',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
